Burk.WebUI/Controllers/SystemController.cs
using Burk.Logic.Abstract.Services;
using Burk.Logic.Concrete.Users.Managers;
using Burk.Model.Users;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Burk.WebUI.Controllers
{
    [Authorize]
    public class SystemController : BaseController
    {
        #region Fields
        private ISystemService service;
        //private ApplicationUserManager userManager;
        #endregion

        #region ctor
        public SystemController(ISystemService _service)
        {
            service = _service;
        }

        public SystemController(ISystemService _service, ApplicationUserManager userManager) : base(userManager)
        {
            service = _service;
        }
        #endregion

        #region GRIDS
        public JsonResult GetListSystems()
        {
            var systems = service.GetAllByUser(CurrentUser.Id);
            var systemsList = systems.ToList();

            var jsonData = from item in systemsList
                           select new
                           {
                               item.SystemId,
                               item.FullName,
                               item.ShortName
                           };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region CRUD
        #region GetAll
        public ActionResult UserSystems()
        {
            return View();
        }
        #endregion

        #region AddEdit
        [HttpGet]
        public ActionResult AddEdit(int systemId = 0)
        {
            Model.UDB.System system = service.GetById("SystemId", systemId.ToString());
            return PartialView("AddEditSystem", system);
        }

        [HttpPost]
        public ActionResult AddEdit(Model.UDB.System model)
        {
            try
            {
                if (model.SystemId == default(int))
                {
                    var returnModel = service.Insert(model, CurrentUser.Id);
                    return Content("SuccessCreate " + returnModel.SystemId);
                }
                else
                {
                    service.Update(model);
                    return Content("SuccessEdit");
                }
            }
            catch (Exception ex)
            {
                return Content("Error");
                throw new Exception("Error in controller", ex);
            }
        }
        #endregion

        #region Delete
        public ActionResult Delete(int systemId)
        {
            try
            {
                service.Delete(systemId);
            }
            catch (Exception)
            {
                return Content("Error");
                throw;
            }
            return Content("Deleted");
        }
        #endregion
        #endregion
    }
}

Burk.WebUI/Views/System/AddEditSystem.cshtml
@model Burk.Model.UDB.System
@using Burk.Model.Resources;

<script type="text/javascript" src="~/Scripts/custom/System/AddEditSystem.js"></script>
@Scripts.Render("~/bundles/jqueryval")
@using (Html.BeginForm("AddEdit", "System", FormMethod.Post, new { id = "addEditSystemDialog" }))
{
    @Html.HiddenFor(x => x.SystemId)
    @Html.HiddenFor(x => x.UID)

    <div class="tb_title">@Html.DisplayNameFor(x => x.FullName):<span class="req">*</span></div>
    <div>@Html.TextBoxFor(x => x.FullName)</div>
    <div>@Html.ValidationMessageFor(x => x.FullName)</div>
    <div class="tb_title">@Html.DisplayNameFor(x => x.ShortName):</div>
    <div>@Html.TextBoxFor(x => x.ShortName)</div>

    <div id="ErrorInputDiv" />
    <div id="SuccessfulCreateDiv" />

    <input id="saveBtn" type="button" class="btn btn-primary btn-sm" onclick="Save()" value="@Resource.Save" />
}

Burk.WebUI/Views/System/UserSystems.cshtml
@using Burk.Model.Resources;
@{
    ViewBag.Title = @Resource.Systems;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript" src="~/Scripts/custom/System/UserSystems.js"></script>

<script type="text/javascript">
    var URLGrid = "@Url.Action("GetListSystems")";
</script>

<h2>@ViewBag.Title</h2>

<div style="height:20px"></div>
<input id="createBtn" type="button" class="btn btn-primary btn-sm" onclick="AddEdit()" value="@Resource.CreateNewSystem"/>
<div id="addEditDialog"></div>
<div id="SuccessDeletedDiv"></div>
<div id="jqxgrid" />
<div></div>