Burk.WebUI/Controllers/DictionaryController.cs
using Burk.Logic.Abstract.Services;
using Burk.Logic.Concrete.Users.Managers;
using Burk.Model.UDB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Burk.WebUI.Controllers
{
    [Authorize]
    public class DictionaryController : BaseController
    {
        #region Fields
        private IDictionaryService dictionaryService;
        #endregion

        #region ctor
        public DictionaryController(IDictionaryService _dicService, ApplicationUserManager userManager) : base(userManager)
        {
            dictionaryService = _dicService;
            ViewBag.IsShowSystemName = true;
            ViewBag.IsShowMenu = true;
        }
        #endregion
        
        public ActionResult Index()
        {
            return View();
        }

        #region GRIDs
        public ActionResult GetListDictionaries(int systemId)
        {
            var dictionaries = dictionaryService.GetDictionaries(systemId);

            var jsonData = from item in dictionaries
                           select new
                           {
                               item.DictionaryId,
                               item.FullName,
                               item.ShortName
                           };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetListValues(int dictionaryId)
        {
            var values = dictionaryService.GetDictionaryValues(dictionaryId);

            var jsonData = from item in values
                           select new
                           {
                               item.DicValueId,
                               item.FullName,
                               item.ShortName
                           };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region CRUD Dictionary
        #region AddEdit
        [HttpGet]
        public ActionResult AddEditDictionary(int dictionaryId)
        {
            var model = dictionaryService.GetById("DictionaryId", dictionaryId.ToString());
            if (string.IsNullOrEmpty(model.FullName))
            {
                model.SystemId = (int)Session["SystemId"];
            }
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult AddEditDictionary(Dictionary model)
        {
            try
            {
                if (model.DictionaryId == default(int))
                {
                    dictionaryService.Insert(model);
                    return Content("SuccessCreate");
                }
                else
                {
                    dictionaryService.Update(model);
                    return Content("SuccessEdit");
                }
            }
            catch (Exception ex)
            {
                return Content("Error");
                throw new Exception("Error in controller", ex);
            }
        }
        #endregion

        #region Delete
        public ActionResult DeleteDictionary(int dictionaryId)
        {
            try
            {
                var model = dictionaryService.GetById("DictionaryId", dictionaryId.ToString());
                dictionaryService.Delete(model);
            }
            catch (Exception)
            {
                return Content("Error");
            }
            return Content("Success");
        }
        #endregion
        #endregion

        #region CRUD Value
        #region AddEdit
        [HttpGet]
        public ActionResult AddEditValue(int valueId, int dictionaryId)
        {
            var model = dictionaryService.GetValueById(valueId);
            if (string.IsNullOrEmpty(model.FullName))
            {
                model.DictionaryId = dictionaryId;
            }
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult AddEditValue(DictionaryValue model)
        {
            try
            {
                if (model.DicValueId == default(int))
                {
                    dictionaryService.InsertValue(model);
                    return Content("SuccessCreate");
                }
                else
                {
                    dictionaryService.UpdateValue(model);
                    return Content("SuccessEdit");
                }
            }
            catch (Exception ex)
            {
                return Content("Error");
                throw new Exception("Error in controller", ex);
            }
        }
        #endregion

        #region Delete
        public ActionResult DeleteValue(int valueId)
        {
            try
            {
                var model = dictionaryService.GetValueById(valueId);
                dictionaryService.DeleteValue(model);
            }
            catch (Exception)
            {
                return Content("Error");
            }
            return Content("Success");
        }
        #endregion
        #endregion
    }
}

Burk.WebUI/Controllers/WorkController.cs
using Burk.Logic.Abstract.Services;
using Burk.Logic.Concrete.Users.Managers;
using Burk.Model.Misc;
using Burk.Model.UDB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Burk.WebUI.Controllers
{
    [Authorize]
    public class WorkController : BaseController
    {
        #region Fields
        private ISystemService systemService;
        private IDossierService dossierService;
        private IInsetService insetService;
        private IDictionaryService dictionaryService;
        private IValueService valueService;
        #endregion

        #region ctor
        public WorkController(IDictionaryService _dicService, IInsetService _insetService, IDossierService _dossierService, ISystemService _service, IValueService _valueService, ApplicationUserManager userManager) : base(userManager)
        {
            systemService = _service;
            dossierService = _dossierService;
            insetService = _insetService;
            dictionaryService = _dicService;
            valueService = _valueService;
            ViewBag.IsShowSystemName = true;
            ViewBag.IsShowMenu = true;
        }
        #endregion

        public ActionResult Index(int systemId, int? dossierId)
        {
            CleanSessions();
            var system = systemService.GetById("SystemId", systemId.ToString());
            Session["SystemName"] = system.FullName;
            Session["SystemId"] = system.SystemId;
            Session["IsWork"] = true;
            if (dossierId != null && dossierId != 0)
            {
                var dossierObject = dossierService.GetById("DosObjectId", dossierId.ToString());
                Session["DossierName"] = dossierObject.FullName;
                Session["DossierId"] = dossierId;
            }
            else
            {
                Session["DossierName"] = null;
                Session["DossierId"] = null;
            }
            return View();
        }

        public ActionResult AddEditObj(int dossierId, int? mainListId, int? insetId, int? systemId)
        {
            int? valueId = null;
            var dossierObject = dossierService.GetById("DosObjectId", dossierId.ToString());
            Session["DossierName"] = dossierObject.FullName;
            Session["DossierId"] = dossierId;
            Session["MainListId"] = mainListId;
            Session["IsWork"] = true;
            if (systemId != null)
            {
                var system = systemService.GetById("SystemId", systemId.ToString());
                Session["SystemName"] = system.FullName;
                Session["SystemId"] = system.SystemId;
            }

            if (mainListId == null)
            {
                Session["IsCreate"] = true;
                Session["ListId"] = null;
            }
            else
            {
                Session["IsCreate"] = false;
                if (insetId == null)
                    valueId = valueService.GetFirstInsetValueIdByMainListId(mainListId.Value);
                else
                    valueId = valueService.GetValueIdByMainListAndInsetId(mainListId.Value, insetId.Value);
                DossierValue valueModel = valueService.GetById("DosValueId", valueId.ToString());
                Session["ListId"] = valueModel.DosListId;
                Session["InsetId"] = valueService.GetInsetIdByValueId(valueId.Value);
                var insetModel = insetService.GetById("DosInsetId", Session["InsetId"].ToString());
                Session["InsetName"] = insetModel.FullName;
            }
            Session["ValueId"] = valueId;

            return View();
        }
    }
}

Burk.WebUI/Views/Shared/_Layout.cshtml
@using System.Globalization;
@using System.Threading;
@using Burk.Model.Misc;
@using Burk.Model.Resources;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/jqueryUI")
    @Styles.Render("~/Content/jqueryUIcss")
    @Styles.Render("~/Content/JQWidgetscss")
    @Scripts.Render("~/bundles/JQWidgets")

    @Scripts.Render("~/bundles/SharedScripts")
</head>
<body>
    <script src="@Url.Content("~/Home/GenerateJS_Of_Resource")" type="text/javascript"></script>
    <script type="text/javascript">
        var UICulture = '@UICulture';
    </script>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Burk", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (ViewBag.IsShowSystemName == true)
                    {
                        <li>@Html.ActionLink(Session["SystemName"].ToString(), "Index", "Work", new { systemId = Session["SystemId"] }, null)</li>
                        if (Session["IsWork"] != null && (bool)Session["IsWork"] == false)
                        {
                            <li>@Html.ActionLink(@Resource.Dictionaries, "Index", "Dictionary")</li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @Html.Partial("_MenuPartial")
    <div class="container body-content">
        @RenderBody()
    </div>

    <footer style="text-align:center">
        <hr />
        <p>&copy; @DateTime.Now.Year - Burk</p>
        @{
            CultureInfo currentCulture = Thread.CurrentThread.CurrentCulture;
            <a href="/Home/ChangeCurrentCulture/@((int)Language.en)">@Resource.English</a> <br />
            <a href="/Home/ChangeCurrentCulture/@((int)Language.ua)">@Resource.Ukrainian</a> <br />
            <a href="/Home/ChangeCurrentCulture/@((int)Language.ru)">@Resource.Russian</a>
        }
    </footer>

    @RenderSection("scripts", required: false)

    <div id="ErrorDiv" />
    <div id="jqxLoader"></div>
    <div id="SuccessDiv"></div>
    <div id="AddEditDiv"></div>
</body>
</html>

Burk.WebUI/Views/Shared/_MenuPartial.cshtml
@if (ViewBag.IsShowMenu != null && ViewBag.IsShowMenu == true)
{
    <script src="~/Scripts/custom/SystemSettings/MenuSettings.js" type="text/javascript"></script>
    <div style="float:left; width:120px">
        <div id='jqxMenu'></div>
    </div>

    <div id="addEditMenuItemDialog"></div>
}